### ISSUE TITLE
Cannot open Tinkercad OBJ files

### ISSUE THREAD

**Issue by Xane123** [castle-engine/view3dscene#11]
As I heard view3dscene can convert files to X3D/VRML, the only main color formats supported by Shapeways, I tried opening an OBJ file from Tinkercad, which stores the model's solid colors in its MTL file. When opening a file from Tinkercad, this error appears:

> Error while loading scene from [file path]: "0.0" is a invalid integer. 

The MTL file it tries to read contains this:

```
# Color definition for Tinkercad Obj File 2015

newmtl color_16089887
Ka 0 0 0 
Kd 0.9607843137254902 0.5137254901960784 0.12156862745098039
d 1.0
illum 0.0

newmtl color_14900002
Ka 0 0 0 
Kd 0.8901960784313725 0.3568627450980392 0.13333333333333333
d 1.0
illum 0.0

newmtl color_16749622
Ka 0 0 0 
Kd 1 0.5803921568627451 0.21176470588235294
d 1.0
illum 0.0

newmtl color_16755294
Ka 0 0 0 
Kd 1 0.6666666666666666 0.3686274509803922
d 1.0
illum 0.0

newmtl color_16249585
Ka 0 0 0 
Kd 0.9686274509803922 0.9490196078431372 0.9450980392156862
d 1.0
illum 0.0

newmtl color_15708628
Ka 0 0 0 
Kd 0.9372549019607843 0.6941176470588235 0.8313725490196079
d 1.0
illum 0.0

newmtl color_16291485
Ka 0 0 0 
Kd 0.9725490196078431 0.5882352941176471 0.615686274509804
d 1.0
illum 0.0

newmtl color_7583832
Ka 0 0 0 
Kd 0.45098039215686275 0.7215686274509804 0.34509803921568627
d 1.0
illum 0.0

newmtl color_16448250
Ka 0 0 0 
Kd 0.9803921568627451 0.9803921568627451 0.9803921568627451
d 1.0
illum 0.0

newmtl color_8768998
Ka 0 0 0 
Kd 0.5215686274509804 0.803921568627451 0.9019607843137255
d 1.0
illum 0.0

newmtl color_4634441
Ka 0 0 0 
Kd 0.27450980392156865 0.7176470588235294 0.28627450980392155
d 1.0
illum 0.0

newmtl color_6550119
Ka 0 0 0 
Kd 0.38823529411764707 0.9490196078431372 0.403921568627451
d 1.0
illum 0.0

newmtl color_1206582
Ka 0 0 0 
Kd 0.07058823529411765 0.4117647058823529 0.21176470588235294
d 1.0
illum 0.0

newmtl color_2829873
Ka 0 0 0 
Kd 0.16862745098039217 0.1803921568627451 0.19215686274509805
d 1.0
illum 0.0

```

# Reproducing
To reproduce this error, just extract the model files from this ZIP file then attempt to open the OBJ file in view3dscene. That error will appear then it will cancel loading the model.

[New Juice Cylinder (1).zip](https://github.com/castle-engine/view3dscene/files/2717680/New.Juice.Cylinder.1.zip)

**Comment by michaliskambi** [comment]
Thanks for the clear report! This was a trivial error:) Fixed now, thanks!

You can get the latest view3dscene build from http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ to try the fix. Please give it about ~15 minutes from now to rebuild :)

![tinker_0](https://user-images.githubusercontent.com/1076978/50563241-6158d300-0d1b-11e9-8fc0-47196993101b.png)
