### ISSUE TITLE
ImageBackground: can **not** animate texCoords!

### ISSUE THREAD

**Issue by elmkni** [castle-engine/view3dscene#19]
Hi Michalis,

based on your ['**animate_tex_coord.x3dv**'](https://raw.githubusercontent.com/castle-engine/demo-models/master/animation/simple_tests_interpolation_and_time/animate_tex_coord.x3dv)-example, I tried to animate the background image:
```
<X3D profile="Full" version="3.3">
  <Scene>

    <Viewpoint/>

    <ImageBackground DEF="IB" color="1 0 1 0.5" texCoords="0 0 1 0 1 1 0 1">
      <PixelTexture DEF="PT" image="2 2 2 0xFFFF 0xFF80 0xFF80 0xFFFF ">
        <TextureProperties magnificationFilter="NEAREST_PIXEL"/>
      </PixelTexture>
    </ImageBackground>

    <Shape DEF='QUAD'>
      <Appearance><Material/><PixelTexture USE="PT"/></Appearance>
      <IndexedQuadSet index="0 1 2 3" solid="true">
        <Coordinate point="-2 -2 2, 2 -2 2, 2 2 2, -2 2 2"/>
        <TextureCoordinate DEF="TC" point="0 0 1 0 1 1 0 1"/>
      </IndexedQuadSet>
    </Shape>
    <Transform rotation='1 0 0  1.5707963268'><Shape USE='QUAD'/></Transform>
    <Transform rotation='1 0 0 -1.5707963268'><Shape USE='QUAD'/></Transform>
    <Transform rotation='0 1 0  1.5707963268'><Shape USE='QUAD'/></Transform>
    <Transform rotation='0 1 0 -1.5707963268'><Shape USE='QUAD'/></Transform>
    <Transform rotation='0 1 0  3.1415926536'><Shape USE='QUAD'/></Transform>

    <TimeSensor DEF="TS" loop="true" cycleInterval="10"/>
    <!--

      ' VBScript: compute texture coordinates for smooth quad rotation

      option explicit

      const S = .70710678118654752440084436210485 ' sqr(.5)
      const T = .01745329251994329576923690768489 ' pi/180 = degree to rad

      dim A,N,K,VALUE,KEY

      for  N =    0 to 360 step 10
       for K = -135 to 135 step 90
        A = ( N + K ) * T
        VALUE = VALUE & round( cos( A ) * S + .5, 5 ) & " "
        VALUE = VALUE & round( sin( A ) * S + .5, 5 ) & " "
       next
       VALUE = VALUE & chr(10)
      next

      wscript.echo( VALUE ) ' print keyValue

      for N = 0 to 36 step 1
       KEY = KEY & round( N / 36, 5 ) & " "
      next

      wscript.echo( KEY ) ' print key

    -->
    <CoordinateInterpolator2D DEF="CI"
      key="
        0
        0.02778 0.05556 0.08333 0.11111 0.13889 0.16667 0.19444 0.22222 0.25
        0.27778 0.30556 0.33333 0.36111 0.38889 0.41667 0.44444 0.47222 0.5
        0.52778 0.55556 0.58333 0.61111 0.63889 0.66667 0.69444 0.72222 0.75
        0.77778 0.80556 0.83333 0.86111 0.88889 0.91667 0.94444 0.97222 1
      "
      keyValue="
        0 0 1 0 1 1 0 1
        0.09442 -0.07923 1.07923 0.09442 0.90558 1.07923 -0.07923 0.90558
        0.20116 -0.14086 1.14086 0.20116 0.79884 1.14086 -0.14086 0.79884
        0.31699 -0.18301 1.18301 0.31699 0.68301 1.18301 -0.18301 0.68301
        0.43837 -0.20442 1.20442 0.43837 0.56163 1.20442 -0.20442 0.56163
        0.56163 -0.20442 1.20442 0.56163 0.43837 1.20442 -0.20442 0.43837
        0.68301 -0.18301 1.18301 0.68301 0.31699 1.18301 -0.18301 0.31699
        0.79884 -0.14086 1.14086 0.79884 0.20116 1.14086 -0.14086 0.20116
        0.90558 -0.07923 1.07923 0.90558 0.09442 1.07923 -0.07923 0.09442
        1 0 1 1 0 1 0 0
        1.07923 0.09442 0.90558 1.07923 -0.07923 0.90558 0.09442 -0.07923
        1.14086 0.20116 0.79884 1.14086 -0.14086 0.79884 0.20116 -0.14086
        1.18301 0.31699 0.68301 1.18301 -0.18301 0.68301 0.31699 -0.18301
        1.20442 0.43837 0.56163 1.20442 -0.20442 0.56163 0.43837 -0.20442
        1.20442 0.56163 0.43837 1.20442 -0.20442 0.43837 0.56163 -0.20442
        1.18301 0.68301 0.31699 1.18301 -0.18301 0.31699 0.68301 -0.18301
        1.14086 0.79884 0.20116 1.14086 -0.14086 0.20116 0.79884 -0.14086
        1.07923 0.90558 0.09442 1.07923 -0.07923 0.09442 0.90558 -0.07923
        1 1 0 1 0 0 1 0
        0.90558 1.07923 -0.07923 0.90558 0.09442 -0.07923 1.07923 0.09442
        0.79884 1.14086 -0.14086 0.79884 0.20116 -0.14086 1.14086 0.20116
        0.68301 1.18301 -0.18301 0.68301 0.31699 -0.18301 1.18301 0.31699
        0.56163 1.20442 -0.20442 0.56163 0.43837 -0.20442 1.20442 0.43837
        0.43837 1.20442 -0.20442 0.43837 0.56163 -0.20442 1.20442 0.56163
        0.31699 1.18301 -0.18301 0.31699 0.68301 -0.18301 1.18301 0.68301
        0.20116 1.14086 -0.14086 0.20116 0.79884 -0.14086 1.14086 0.79884
        0.09442 1.07923 -0.07923 0.09442 0.90558 -0.07923 1.07923 0.90558
        0 1 0 0 1 0 1 1
        -0.07923 0.90558 0.09442 -0.07923 1.07923 0.09442 0.90558 1.07923
        -0.14086 0.79884 0.20116 -0.14086 1.14086 0.20116 0.79884 1.14086
        -0.18301 0.68301 0.31699 -0.18301 1.18301 0.31699 0.68301 1.18301
        -0.20442 0.56163 0.43837 -0.20442 1.20442 0.43837 0.56163 1.20442
        -0.20442 0.43837 0.56163 -0.20442 1.20442 0.56163 0.43837 1.20442
        -0.18301 0.31699 0.68301 -0.18301 1.18301 0.68301 0.31699 1.18301
        -0.14086 0.20116 0.79884 -0.14086 1.14086 0.79884 0.20116 1.14086
        -0.07923 0.09442 0.90558 -0.07923 1.07923 0.90558 0.09442 1.07923
        0 0 1 0 1 1 0 1
      "
    />

    <ROUTE fromNode="TS" fromField="fraction_changed"
             toNode="CI"   toField="set_fraction"/>
    <ROUTE fromNode="CI" fromField="value_changed"
             toNode="IB"   toField="set_texCoords"/>
    <ROUTE fromNode="CI" fromField="value_changed"
             toNode="TC"   toField="set_point"/>

    <KeySensor DEF="KS"/>
    <BooleanFilter DEF="BF"/>

    <ROUTE fromNode="KS" fromField="controlKey"
             toNode="BF"   toField="set_boolean"/>
    <ROUTE fromNode="BF" fromField="inputNegate"
             toNode="TS"   toField="set_enabled"/>
  </Scene>
</X3D>
```

**but ImageBackground seems to ignore everything**, despite the fact, that it **does not ignore vertical or horizontal scaling** via texCoords!

You wrote, that ['ImageBackground rendering is a little special'](https://github.com/castle-engine/view3dscene/issues/18) -- is that the cause or **am I missing something?**

BTW.: 
- It would be cool, **if the user could set the default screen geometry** in the '**Preferences**'-**menu** of **View3DScene** (so that it ends up in the '**view3dscene.conf**' file) and **View3DScene** from that point on **would always start with the prefered screen size** -- the example above for instance only works acceptable for **quadratic ImageBackground**s.

- I think it would have been more 'elegant' to use a **spline based interpolation** for the computation of the texture coordinates, but **SplinePositionInterpolator2D** is for **SFVec2f**-output only. I tried to compensate the **linear interpolation** of **CoordinateInterpolator2D** by using 36 x 4 different s,t positions on the circular circumfence of the quad ...

- Some of your **animation examples** on [github](https://github.com/castle-engine/demo-models/tree/master/animation/simple_tests_interpolation_and_time) (like animate_tex_coord.x3dv) were appearantly **shifted to a deeper nested directory**, so that **all the texture/movie_texture references do not work** anymore. In [demo_models-3.9.0.zip](https://downloads.sourceforge.net/castle-engine/demo_models-3.9.0.zip) everything seems to be alright.

- I still couldn't find the reason, why **InstantPlayer doesn't run on my system** -- does it need
**Win10 Professional**, a pure **Intel** processor as stated [here](http://doc.instantreality.org/tutorial/installation-on-windows) (I've got a **AMD E1-2500** mobility APU) or some exotic **additional libraries/.dlls**? -- I have trieded dozens of things, like **installing as administrator**, installing the **old 32-bit versions of InstantReality**, copying the **mfc/vcrt120.dlls** into **InstantRealitiy's bin-directory**, using **sfc.exe** and **dism.exe** to check for **integrity faults in Win10's component store** (WinSxS) and **repair them** etc. -- **nothing worked: still error 0xC000007B** -- and _according to the internet, I am the only one among 7 billion inhabitants of this planet, who is experiencing this problem_ :(

But never mind -- if you **please** could:
- add a geometry option to 'Preferences'-menu and 'view3dscene.conf'-file and
- fix the ImageBackground texCoords animation issue or
- tell me where I am mistaken,

I would be glad. 

Please keep in mind, that **I can not test** my **X3D** files with **InstantPlayer** [see above] to see, if they work there -- **so don't be angry at me, if I ask for something, that does not even work with InstantPlayer**.

With best regards,

Elmar

P.S.: here are the test files: [view3dscene_issue_19.zip](https://github.com/castle-engine/view3dscene/files/3562764/view3dscene_issue_19.zip)

**Comment by michaliskambi** [comment]
Indeed, I didn't implement animating of `texCoords` on `ImageBackground`. I'll fix it soon (tomorrow probably). It's indeed because `ImageBackground` rendering is "special".

As for the geometry -- I would advise to do it differently. Create a shell script ("batch" script in Windows), that contains a command like `view3dscene --geometry 512x512`. Save it in a file like `my_view3dscene.bat` and execute `my_view3dscene.bat` instead of running `view3dscene.exe`.

This is a safer solution, since this way you will not "forget" about such preference. And it's more flexible. You can use this technique to use a lot of other view3dscene command-line options, e.g. `--fullscreen`, pass a specific X3D filename to open etc.

Don't worry about testing with _Instant Reality_, it's not like I want to be "limited" to support only what _Instant Reality_ supports :) Animating `ImageBackground.texCoords` makes sense, it should work, regardless of _Instant Reality_ :)

**Comment by michaliskambi** [comment]
P.S. Thanks for the note about invalid URLs in https://github.com/castle-engine/demo-models , I fixed them now.

**Comment by elmkni** [comment]
Hi Michalis,

**new month -- new luck:**

I finally found a version of **InstantReality** framework (from ftp://ftp.igd.fraunhofer.de/irbuild/Windows-i686/archive/InstantReality-Windows-vs2008-x86-2.3.0.25322.msi) **that doesn't crash** or has any other issues (like **missing 'libLAS.dll'** etc.).

It's **old** (version 2.3.0 from 17.07.2013) and **only 32 bits** but apart from that **works like a breeze!**

![Elmar's dancing pattern box](https://user-images.githubusercontent.com/53652478/64101476-3de49d00-cd6e-11e9-901b-4bcd5fe5ddf1.png)

Originally I also wanted to animate the ImageBackground **color**, but there's **no ColorInterpolatorRGBA**!
Neither [**InstantRealityPlayer**](https://doc.instantreality.org/documentation/component/Interpolation) nor [**X3D v4.0**](http://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-WD1/Part01/components/interpolators.html#Nodereference) has it! -- _This should be proposed to the **Web3D** commitee!_

What really is cool about **InstantPlayer**: it supports to **set the window size** (and anti-aliasing) from **within** the **X3D**-file!
```
<X3D profile="Full" version="3.3">
  <Engine>
    <RenderJob>
      <WindowGroup>
	<Window size='512 512' sample='8' sampleFilterMode='nicest'/>
      </WindowGroup>
    </RenderJob>
  </Engine>
  <Scene>
    ...
  </Scene>
</X3D>
```
This is a much better approach than **batch files**, which **circumvent** MS-Windows's **file-association-mechanism**, where I click on a **X3D**-file and it opens with **View3DScene** or **InstantPlayer**, depending on to which executable the **.x3d**-suffix is set!

That's **even better** than putting the resolution/geometry information into **view3dscene.conf**!

- Would be nice if **View3DScene** also (partially) supported **InstantPlayer**'s **Engine/Window** node!

With best regards,

Elmar

P.S.: here are my test files: [view3dscene_issue_19-1.zip](https://github.com/castle-engine/view3dscene/files/3565516/view3dscene_issue_19-1.zip)

**Comment by elmkni** [comment]
Hi Michalis,

I have just tested `view3dscene-3.18.0-win64-x86_64.zip | 2019-09-04 16:05 | 4.0M | Latest Windows version (64-bit)`, but it still **doesn't allow to animate** the **texCoord** property of  **ImageBackground**!

**Please help!**

With best regards,

Elmar

**Comment by michaliskambi** [comment]
Indeed. Sorry, I simply didn't yet find the time to implement it. This task is on my to-do list, but it's a crowded list now :) I'll try to do it this weekend.

**Comment by michaliskambi** [comment]
Done :)

( As it happens, I was sitting to this when you wrote the last email to me today :) ).

A new version of view3dscene should be available in ~15 minutes on http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/  as usual. 

I have also added your testcase to demo-models, to https://github.com/castle-engine/demo-models/blob/master/background/background_image_animated.x3d . Please let me know if you don't want this, I'll remove it then. (The demo-models are distributed on open-source GNU GPL >= 2 license, see the bottom of https://github.com/castle-engine/demo-models ).

**Comment by michaliskambi** [comment]
P.S. Note that I have created nice docs for `ImageBackground` on https://castle-engine.io/x3d_implementation_environmentaleffects_extensions.php , and also just improved how transparent `ImageBackground` (in case the texture or color has alpha) interacts with underlying color.

**Comment by elmkni** [comment]
Hi Michalis,

Sorry for my late answer, but my **internet was down** for several hours, probably because of the fifty years old TeleCom phone lines (urgh!!!)

**Thank you** for enabling **fixed shader pipeline** for me again and of course for trying to fix **texCoords animation** in **ImageBackground** node, but sadly **it doesn't behave at all like in InstantPlayer!**

![background_image_still_pattern_8080](https://user-images.githubusercontent.com/53652478/64480393-33d7f980-d1c7-11e9-9832-a436f8fdf8b3.png)
[background_image_still_pattern_8080.png]

The background simply **scales the texture horizontally and vertically** (at least it's animated!), but **does not rotate the pattern**, as it does in **InstantPlayer**! -- Is that again a **fixed/pure shader issue**?

You probably also noted the **different coloring** (especially of the background). The reason seems to be, that **InstantPlayer** _discards the alpha channel_ of the pattern and then _multiplies it with the background RGBA color!_ That's why I used `image="2 2 2 0xFFFF 0x8080 0x8080 0xFFFF"` and not `image="2 2 2 0xFFFF 0xFF80 0xFF80 0xFFFF"`, which works fine in **View3DScene-3.18.0-64bit** but not in **InstantPlayer-2.3.0-32bit**! -- (I prefer View3DScene's behavior!)

![background_image_still_pattern_FF80](https://user-images.githubusercontent.com/53652478/64480396-3f2b2500-d1c7-11e9-93b6-479f80a03014.png)
[background_image_still_pattern_FF80.png]

I'm afraid you have to fix the animated texCoords issue again -- sorry!

But **please** leave View3DScene's color behavior as it is!

I include an improved version of [this](https://github.com/castle-engine/demo-models/blob/master/background/background_image_animated.x3d), which not only uses 0xFF80 but also animates the texture **and** the cube! If you like it, **put it to the demo-models!**

BTW: you can stop the animation by pressing **CTRL**! (does not work in InstantPlayer)

With best regards,

Elmar

P.S.: here are the files: [view3dscene_issue_19-2.zip](https://github.com/castle-engine/view3dscene/files/3587057/view3dscene_issue_19-2.zip)

**Comment by michaliskambi** [comment]
Ah, I didn't think of using texCoords to rotate the texture. I didn't even realize that you do it in testcase. This will not work (as you found out) and is a bug. There is no difference here between fixed and shader pipeline.

I know how to fix it. It will require a bit of work, will be done in a few days.

Thank you for testing. I'll let you know when it's fixed.

As for the behavior of color, I did it deliberately and also think it's better. We use color alpha, and we use texture alpha, and we multiply them. If it is partially-transparent, it will be mixed with default background color. This is documented on https://castle-engine.io/x3d_implementation_environmentaleffects_extensions.php , and I also don't think we should change it.

**Comment by michaliskambi** [comment]
Rendering of the `ImageBackground` was rewritten. This fixes this issue -- `texCoords` are now supported fully, and the animation inside your testcase is OK.

Also:

- The new code has other benefits: it is more consistent with the rest of the X3D rendering.

- In particular `MovieTexture` is now supported too inside `ImageBackground.texture`. I added a demo to demo-models, https://github.com/castle-engine/demo-models/blob/master/background/image_background/background_movie.x3dv . All ImageBackground demos are now in one directory, https://github.com/castle-engine/demo-models/tree/master/background/image_background .

- I also updated docs on https://castle-engine.io/x3d_implementation_environmentaleffects_extensions.php a bit.

As usual, new view3dscene should be available on http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ in ~15 minutes.

**Comment by elmkni** [comment]
Hi Michalis,

sorry again for my late answer, but I was testing the latest build of **View3DScene** with your fix:
`view3dscene-3.18.0-win64-x86_64.zip | 2019-09-23 03:07 | 4.0M | Latest Windows version (64-bit)`

### Wow, it works perfectly:
![background_image_animated](https://user-images.githubusercontent.com/53652478/65445262-14310a00-de32-11e9-82de-6617cb78fe53.png)

The image above is an **animated PNG**. You should see a 1-sec-animation **if your browser is up to date**!

The Animated Portable Network Graphics ([**APNG**](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/APNG)) file format is an extension to the Portable Network Graphics ([**PNG**](https://www.w3.org/TR/2003/REC-PNG-20031110)) specification. It allows for **animated PNG files** that work similarly to **animated GIF files**,  while supporting **24-bit images** and **8-bit transparency** as you can see here:
![flame](https://user-images.githubusercontent.com/53652478/65448147-6ecd6480-de38-11e9-8fd4-689b6cb0397a.png)

**APNG** is supported by up to date versions of [**Chrome**](https://www.google.com/chrome), [**Firefox**](https://www.mozilla.org), [**Safari**](https://support.apple.com/downloads/safari), [**Opera**](https://www.opera.com) and  the new [**Chromium-based Microsoft Edge**](https://www.microsoftedgeinsider.com) internet browser. [**FFmpeg**](http://ffmpeg.org) and [**XNview**](https://www.xnview.com) also support **APNG**s.

- ***You should consider*** to support **APNG** as **MovieTexture** via e.g. [**Vampyre Imaging Library**](http://imaginglib.sourceforge.net/) ;)

I attach a **ZIP** with my **inproved version** of `background_image_animated.x3d` **to be added** to your **demo-models/background/image_background** repository **replacing the old** `background_image_animated.x3d`!

- It also contains both **APNG**s and the **batch files to create them**!

I only used [**View3DScene**](https://castle-engine.io/view3dscene.php) (for producing twenty-five 24bit PNGs), [**PNGquant**](https://pngquant.org) (for **optionally** reducing color depth to 8bit) and [**APNGasm**](http://apngasm.sourceforge.net) (to create the actual optimized **animated PNG** with **25 fps**)!

The **flame animation** above, for instance, was produced with `APNGasm flame.png *.png 1 25` in my copy of your **demo-models/movie_texture/flame/seamless** directory!

### Thank you very much!
***for all your tedious work*** to make **texCoords** animation work properly!

With best regards,

Elmar

P.S.: here are the files: [view3dscene_issue_20-3.zip](https://github.com/castle-engine/view3dscene/files/3643766/view3dscene_issue_20-3.zip)

**Comment by michaliskambi** [comment]
Thanks for testing! 

Since APNG is already supported by ffmpeg, it may be trivial to add simple view3dscene support for it. I'll look into it soon.

**Comment by michaliskambi** [comment]
And thank you for the updated background_image_animated.x3d -- I committed it to demo-models.

**Comment by elmkni** [comment]
Hi Michalis,
 
on [https://castle-engine.io/x3d_implementation_texturing.php](https://castle-engine.io/x3d_implementation_texturing.php) you wrote:
 

> We can also open movies from images sequence. This doesn't require ffmpeg, and allows for some tricks (movie texture with alpha channel).
 
Because of that, I proposed the idea of using animated PNGs as partially transparent movie textures.
 
**Now I have found out, that it is indeed possible to create partially transparent MP4 movies and use them as movie textures in View3DScene!**
 
I made use of the fact that FFmpeg is able to copy a sequence of PNG files into a MP4 container.
 
It was quite simple:
```
:: create temporary directory
md temp
 
:: X3D animation -> 100 PNG images
View3DScene background_image_animated.x3d --geometry 512x512 --anti-alias 6 --no-sound
--viewpoint 0 --screenshot-transparent --screenshot-range 12 0.04 100 temp\temp@counter(3).png
 
:: reduce image size (adds '-or8' to filename)
PNGquant --strip --ordered --speed=1 --quality=50-90 temp\*.png
 
:: 100 PNG images -> MP4 with transparency!
FFmpeg -i temp/temp%%03d-or8.png -r:v 25 -c:v copy -map 0:v -t 4 -shortest
-y background_image_animated.mp4
 
:: cleanup
rd/s/q temp
```
- I have **attached a ZIP** with the conversion batch files, the resulting MP4 and APNG files and a X3D movie texture test file: [**view3dscene_issue_19-4.zip**](https://github.com/castle-engine/view3dscene/files/3657042/view3dscene_issue_19-4.zip)

- **You can add the files to your demo-models/movie_texture repository if you like!**
 
BTW: the resulting MP4 file is only slightly bigger (407 kb) than the animated PNG (391 kb) produced with the same optimizations!
 
With best regards,
 
Elmar
 
P.S.: the MP4/APNG files can **not** be viewed in XNview (shows an error) but **show alright in FFplay!**

**Comment by michaliskambi** [comment]
Thank you for testing and info. I'll play around with it on the weekend.

P.S. I also saw your email in which in you send the same thing :) Sorry for not answering earlier, no time.

**Comment by elmkni** [comment]
Hi Michalis,

in the meantime I have tested further **video codecs that support transparency**:

- **png** 8bit (with palette) [MP4]
- **png** 32bit [MP4]
- **qtrle** 32bit (quicktime run-length-encoded) [MOV]
- **v408** 32bit (yuva444p) [MOV]
- **rawvideo** 32bit  [AVI]

Some of the files are very big (**v408** and **rawvideo**), but **qtrle** is acceptable.
**All work with View3DScene/FFmpeg** but do **not** play in **InstantPlayer** or **OctagaPlayer**.
The **paletted 8bit png video shows in freeWRL**, but not completely correct (for unknown reasons).

With best regards,

Elmar

P.S.: as always I attach the test files: [view3dscene_issue_19-5.zip](https://github.com/castle-engine/view3dscene/files/3665376/view3dscene_issue_19-5.zip)

**Comment by elmkni** [comment]
Hi Michalis,

I found a **minor issue** when **FFmpeg** is used.

In [**castlevideo.pas**](https://github.com/castle-engine/castle-engine/blob/master/src/images/castlevideos.pas) you use `FfmpegExecute(Executable, [ '-i', MovieFileName, '-y', '-qscale', '1', '-vframes', IntToStr(MaximumVideoLength), '-f', 'image2', FfmpegTemporaryImagesPattern ]);` to read in images/videos,

but **FFmpeg warns:** `Please use -q:a or -q:v, -qscale is ambiguous`

although the [**FFmpeg documentation**](http://ffmpeg.org/ffmpeg-all.html#Main-options) says:

> -q[:stream_specifier] q (output,per-stream)
> -qscale[:stream_specifier] q (output,per-stream)
> 
> Use fixed quality scale (VBR). The meaning of q/qscale is codec-dependent. If qscale is used without a stream_specifier then it applies only to the video stream, this is to maintain compatibility with previous behavior and as specifying the same codec specific value to 2 different codecs that is audio and video generally is not what is intended when no stream_specifier is used.

- So probably, because at the moment **audio is not extracted**, it would be nice to change '**-qscale**' in [**castlevideo.pas**](https://github.com/castle-engine/castle-engine/blob/master/src/images/castlevideos.pas) into '**-qscale:v**' or '**-q:v**' to get rid of the warning. -- I have tested it: **it works alright!**

- This **change seems to be compatible** with [**AVconv**](https://www.libav.org/), according to its [documentation](https://libav.org/documentation/avconv.html#Main-options).

Also I found a reference to 'http://ffmpeg.mplayerhq.hu/' in  [**castlevideo.pas**](https://github.com/castle-engine/castle-engine/blob/master/src/images/castlevideos.pas), which **seems not to exist anymore** and is re-directed to 'http://ffmpeg.org/' anyway.

With best regards,

Elmar
