### ISSUE TITLE
Material node changed behavior after introduction of PhysicalMaterial/UnlitMaterial

### ISSUE THREAD

**Issue by elmkni** [castle-engine/view3dscene#27]
Hi Michalis,

it's me, Elmar (again).

I recently stumbled over a **regression issue** in the newest CGE/View3DScene:

`view3dscene-3.18.0-win64-x86_64.zip - 2020-04-01 08:27`

Since the introduction of `PhysicalMaterial/UnlitMaterial` the old (v3.x-style)
Material node behaves differently regarding emissiveColor and its relation to
diffuseColor.
```
#X3D V3.3 utf8
PROFILE Full
Shape {
 appearance Appearance {
  material Material { diffuseColor 0 0 0 emissiveColor 1 0 0 }
 }
 geometry Box {}
}
```
used to produce a pure emissive red material -- but now its **pitch black** and
by this **breaks backward compatibility** to over 1500 of my VRML/X3D-files.

Increasing the amount of diffuseColor just a tiny bit, like so:
```
#X3D V3.3 utf8
PROFILE Full
Shape {
 appearance Appearance {
  material Material { diffuseColor 1e-6 1e-6 1e-6 emissiveColor 1 0 0 }
 }
 geometry Box {}
}
```
brings back the original behavior that worked for many years...

You probably understand, that I would rather not change all my existing files
to comply with the new behavior - though I intend to use UnlitMaterial in
future files as soon as X3D v4.0 is official.

Meanwhile I use:
```
#X3D V3.3 utf8
PROFILE Full
Shape {
 appearance Appearance {
  texture PixelTexture { image 1 1 3 0xFF0000 }
 }
 geometry Box {}
}
```
which is shorter and an acceptable workaround for the time beeing...

**I hope it is possible to fix this, without tempering with the new PBR features!**

With best regards,

Elmar

P.S.:

The new glTF/glb feature (skinned animation) is **really cool** - though it does
not work with all files I've tested so far, e.g. "**Bee.glb**" that came with
Microsoft's 3D-Viewer v5.1811.27012.0: it takes very long to load (normal),
**does not display any of the textures** (just dull grey) and the **animations are
extremly slowly** - even when I throttle up animation speed to maximum!

**PasGLTFViewer** (https://github.com/BeRo1985/pasgltf) has no issues with "**Bee.glb**"!

You can download "**Bee.glb**" (20MB) from:

https://github.com/leation/mydata/raw/master/Bee.glb

**Comment by michaliskambi** [comment]
Fixed (in commit https://github.com/castle-engine/castle-engine/commit/e6d96db3069d011b59d5071636073f6c1be6c9be ). It was broken for older GPUs (where we have to use an older "fixed-function" pipeline for rendering), it was working on new GPUs so I didn't notice this regression.

Thanks for testing!

The new version should be on http://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ in ~15 minutes.

BTW, note that there have been some changes in how we treat `Material` diffuse and emissive. In short, it is now *more* correct, with respect to the X3D 3 specification. See https://castle-engine.io/wp/2020/03/07/physically-based-rendering-and-lots-of-other-lighting-materials-upgrades-in-castle-game-engine-and-x3d-4-0/ , section _Backward compatibility_. Of course it was never intended to break the working of `Material.emissiveColor` :)

As for glTF: This is a work in progress. Both PBR materials and animations will be optimized in the future. Please feel free to report bugs/slowness on particular glTF models, as separate tickets.

**Comment by elmkni** [comment]
Hi Michalis,

I have tested `view3dscene-3.18.0-win64-x86_64.zip - 2020-04-02 12:48` and everything is OK now!

**Thanks a lot** for the quick respond and fix!

With best regards,

Elmar

**Comment by michaliskambi** [comment]
@elmkni I've been doing lots of improvements and optimizations to glTF lately (see recent news https://castle-engine.io/wp/ ). In effect the Bee model, that you linked above, now correctly opens, with texture, and it animates with 60 FPS :)

It can be already tested with latest view3dscene on https://michalis.ii.uni.wroc.pl/view3dscene-snapshots/ .

Note that it doesn't (yet) look exactly like it should -- because it uses PBR specular-glossiness parameters, and doesn't contain PBR metallic-roughness parameters. We support it only partially. A warning about it is done. For now, one should provide materials using PBR metallic-roughness parameters, which is part of glTF 2.0 specification (PBR specular-glossiness is only an extension).

**Comment by elmkni** [comment]
Hi Michalis,

it's me Elmar.

Sorry for the late response, I had not checked my emails for some time, so that I overlooked your message, but I already  have tested the latest **(3.19.0-win64**) version of View3DScene and indeed 
**the bee now has a texture and moves really fast and smooth!**

**Thanks very much -- View3DScene is great!**

Elmar
