### ISSUE TITLE
GLTF Import Issue

### ISSUE THREAD

**Issue by peardox** [castle-engine/view3dscene#34]
Wasn't sure whether to put this in CGE or here but found it here so...

Kenney stuff is all CC0 so perfect for CGE...

Go grab the latest Kenney pack - https://www.kenney.nl/assets/city-kit-suburban

Extract it and navigate to Models/GLTF format

Try opening one of the *.glb models - Access Violation under Ubunto 20 + Windows 10

Works in Blender...

The OBJ is fine

**Comment by michaliskambi** [comment]
Thank you! Indeed it was a (simple) bug on our side, fixed in CGE now.
