### ISSUE TITLE
Exception "EAccessViolation": Access violation

### ISSUE THREAD

**Issue by ricklentz** [castle-engine/view3dscene#38]
The view3dscene command-line options to --write-encoding=xml appear to fail with an **_Exception "EAccessViolation": Access violation_** when attempting to convert a GLTF object to X3D.  The same process performed through the GUI menus with the same model works without issue.

To replicate this issue, pick one of the GLTF examples in [https://castle-engine.io/demo_models.php]( https://castle-engine.io/demo_models.php) and upload with defaults to [https://castle-engine.io/convert.php](https://castle-engine.io/convert.php).  The service returns error code zero.  Closer inspection on a local build reveals that view3Dscene produces "Exception "EAccessViolation": Access violation" which may reflect the same issue causing failures in [https://castle-engine.io/convert.php](https://castle-engine.io/convert.php).

**Comment by brutzman** [comment]
Cosmetic for consistency: also suggest removing space character and adding period, "Classic VRML (x3dv extension)" to "ClassicVRML (.x3dv extension)"

**Comment by michaliskambi** [comment]
1. https://castle-engine.io/convert.php answering `Conversion script failed (non-zero exit status)`: fixed. That is, we didn't display full error message, when you forget to upload glTF binary data. The error message will now appear OK. And you should upload additional binary data.

    You most likely uploaded the `xxx.gltf` file without the corresponding `xxx.bin` file (that contains vertex data). E.g. you uploaded `gltf/punctual_lights/test_lights.gltf`, but not `gltf/punctual_lights/test_lights.bin` . When a glTF model references additional binary files. you *have* to upload them too (as the comments under https://castle-engine.io/convert.php say, you can select multiple files by _Ctrl_ in the open dialog box).

    Our error message did not communicate it. Now you will see

    ```
    Exception "EDownloadError":
    Error when downloading "file:///home/convert-to-x3d/test_lights.bin": Exception "EFOpenError":
    Unable to open file "/home/convert-to-x3d/test_lights.bin"
    Conversion script failed (non-zero exit status).
    ```

    In case of trouble, please provide more details about what do you do / which file you use. The first glTF I tested from https://castle-engine.io/demo_models.php was `gltf/knight_size_test/knight_size_test.glb`, and it worked :), as it contains glTF per-vertex data embedded. In general a glTF (with `.gltf` extension) file may reference additional binary files, but doesn't have to -- it depends on how it was exported. Only the glTF files with `.glb` extension are always self-contained.
    
    Also note that https://castle-engine.io/convert.php is actually using `tovrmlx3d` (additional binary bundled with `view3dscene`, and executes it like `tovrmlx3d --encoding=xml input.xxx > output.x3d`).

2. view3dscene making access violation: hm, I cannot reproduce it. I tested using `--write-encoding` locally, with

    - view3dscene stable from https://castle-engine.io/view3dscene.php
    - view3dscene snapshot from https://castle-engine.io/view3dscene.php
    - view3dscene built locally

    I tested like this:

    ```
    view3dscene ~/sources/castle-engine/demo-models/gltf/punctual_lights/test_lights.gltf --write --write-encoding=xml  > something.x3d
    ```

    and it goes OK. So

    - What exactly do you run, on which input file do you run it?

    - What OS do you use? I tested above now on Linux/x86_64.

> Cosmetic for consistency: also suggest removing space character and adding period, "Classic VRML (x3dv extension)" to "ClassicVRML (.x3dv extension)"

I added a period. I didn't remove the space, I like it :), it separates 2 words, and various engine docs talk about _classic VRML encoding_, not _ClassicVRML encoding_. So I don't make ClassicVRML a single word.

**Comment by ricklentz** [comment]
@michaliskambi   Thank you.  Regarding 2 above, the exception can be triggered when running it without the pipe-to-file (' > something.x3d') portion of the command.  Works perfectly when used per the documentation.  ;-) Thank you again!

**Comment by michaliskambi** [comment]
@ricklentz Aha, we can improve the error in this case then :)

Done, instead of "EAccessViolation" you will now see clear 

```
Standard output is not available. This most likely means you used --write option on Windows and you didn't redirect the output.

The proper usage from the command-line looks like "view3dscene input.gltf --write > output.x3d", see https://castle-engine.io/view3dscene.php#section_converting .
```

![conv_error](https://user-images.githubusercontent.com/1076978/121900766-133abd00-cd26-11eb-83af-3f61aa017a0d.png)

**Comment by michaliskambi** [comment]
The automatic "snapshot" build from https://castle-engine.io/view3dscene.php will soon contain this improvement.
