### ISSUE TITLE
Exporting to formats more commonly used in CAD programs

### ISSUE THREAD

**Issue by DavidGriffith** [castle-engine/view3dscene#44]
I've been looking for something to easily convert Collada (`.dae`) models from Sketchup into something commonly read by CAD programs preferably `.step`.  `view3dscene` loads `.dae` files wonderfully, but the `.x3d` format is troublesome.  Is there any chance of adding support for `.step`?

**Comment by michaliskambi** [comment]
Not likely, I'm afraid, after a quick research about STEP.

https://all3dp.com/2/step-file-format-simply-explained/
https://www.adobe.com/pl/creativecloud/file-types/image/vector/step-file.html
https://en.wikipedia.org/wiki/ISO_10303-21
https://www.iso.org/standard/63141.html

1\. The STEP format is not common in the domain of game development, so adding this to _Casle Game Engine_ would be a burden we need to maintain, while not many people use it.

2\. The STEP format is not very good, compared to e.g. glTF or X3D.

2.1. _"STEP files also can’t save a specific material, texture, or lighting of a model, as these elements are disregarded when a model is saved as a STEP file."_ ( https://all3dp.com/2/step-file-format-simply-explained/ ) - this is less features than glTF, X3D and most other 3D formats

2.2. _"the specification is not freely available (you have to pay for it)"_ ( https://en.wikipedia.org/wiki/ISO_10303-21#Criticism ) - this makes the specification beyond our reach (even if some people can pay for it, not everyone will have access to it, so working on it in open-source fashion is impossible)

We may introduce at some point ability to save 3D models to glTF, not just X3D. But I'm afraid STEP doesn't look like a good candidate for us.

I understand it has advantages (popular in CAD software; standardized by ISO) but these do not outweight the problems, in particular 2.2.
