### ISSUE TITLE
Multiple Problems with latest View3DScene

### ISSUE THREAD

**Issue by elmkni** [castle-engine/view3dscene#45]
Hi Michalis,

it's me again, Elmar...

I just found some problems with View3DScene.exe from 12-Jun-2022 19:30: https://jenkins.castle-engine.io/public/builds/view3dscene/view3dscene-4.1.0-win64-x86_64.zip

1) TextureProperties {} does not set the defaults (like: magnificationFilter to "FASTEST") anymore.
   See: https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texturing.html#TextureProperties
   This forces me to manually alter hundreds of files that are carefully formatted to keep a 80 characters line limit...

2) PLUG_texture_apply is now deprecated.
   View3DScene gives the following error message:

> Using PLUG_texture_apply is deprecated. Upgrade to 1. PLUG_main_texture_apply (to do something after main texture application; but remember that it happens *before* lighting application in case of Phong shading), 2. or PLUG_fragment_modify (to do final fragment color adjustment)

   You had fixed this in 2020:

>    https://github.com/castle-engine/view3dscene/issues/24
>    michaliskambi commented on 11 Mar 2020
>    I pushed a simple fix to enable PLUG name texture_apply for backward compatibility.

   This forces me to manually alter hundreds of files that are carefully formatted to keep a 80 characters line limit...

3) Export to JP2 (JEPEG2000) files does not work at all.
   View3DScene gives the following error message (that cannot be send to clipboard):

> Unable to save screen: Cannot save image to file format jp2 using Vampyre Imaging

Please help...

with best regards,

Elmar

**Comment by michaliskambi** [comment]
1. The defaults are set correctly. 

    However, the default `TextureProperties.magnificationFilter` and `TextureProperties.minificationFilter` in X3D 4 have changed (and we apply this change to all X3D versions in CGE/view3dscene) from `FASTEST` to `DEFAULT`. See X3D 4 : https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/texturing.html#TextureProperties .

    And this was a deliberate and good change. The `FASTEST` was not a good default (it caused surprises for people adding `TextureProperties` to control something else than filtering, like `TextureProperties { anisotropicDegree 8 }`, as their textures unexpectedly switched to worse filtering). It also caused some X3D browsers to misinterpret `FASTEST` as "not really fastest, but bilinear" to shield users from this trap.

    So this was a deliberate change. I understand that it causes you additional work, but it's just a good change, and I want to apply it in CGE/view3dscene for all X3D versions for simplicity.

2. Yes, `PLUG_texture_apply` is deprecated -- as it was for a long time. Nothing changed here, we just tell you about it now using a warning.

    As I wrote in https://github.com/castle-engine/view3dscene/issues/24#issuecomment-597249763 : _I can make the texture_apply working again, just deprecated._  . I did not "undeprecate" it in https://github.com/castle-engine/view3dscene/issues/24 , I just made it "still supported". But you should still upgrade to `PLUG_main_texture_apply` (or some other plug documented on https://castle-engine.io/compositing_shaders_doc/html/section.fragment_plugs.html ).

    We now just have a clear warning saying that it is deprecated. So again, I'm sorry this is causing you additional work -- but it is a change I consider good. The name `PLUG_texture_apply` is very confusing when you consider that material may be affected by many textures (specular, ambient, metallic-roughness etc.). That plug only affects the "main" texture in fact. See https://castle-engine.io/compositing_shaders_doc/html/section.fragment_plugs.html for details what is "main texture".

3. JP2 (JPEG2000) - unfortunately it indeed only works on certain platforms for now. Fixing this requires a change in Vampyre Imaging Library we use underneath (without which we could not handle JPEG2000 at all).
