### ISSUE TITLE
Cannot click buttons on macOS Retina screen

### ISSUE THREAD

**Issue by janadamec1** [castle-engine/view3dscene#47]
When running view3dscene on macOS (I have macOS 13.1 Ventura), I cannot click on any toolbar button. When I run menu command Help - About, I cannot even click the Close button, but I can close the About box using Enter.

Tested both on the stable release (v4.2.0) and daily snapshot (v4.3.0).

It seems the scene steals all mouse clicks, as I can drag-rotate the scene when I click on the toolbar buttons.

**Comment by janadamec1** [comment]
Debugged: control positions include scaling (they are used for rendering), but mouse position not. i.e. mouse at [1000,10] hovers over control with rect around [2000,20].

**Comment by janadamec1** [comment]
Fixed in https://github.com/castle-engine/castle-engine/commit/f1442b812bd316aae6ce0de89944ad4949035846. Still can be improved by scaling the view3dscene by DPI

**Comment by janadamec1** [comment]
Will be fixed in https://github.com/castle-engine/view3dscene/pull/51

**Comment by michaliskambi** [comment]
I understand this is solved now by https://github.com/castle-engine/view3dscene/pull/51 . Thanks again for patience, closing!
