### ISSUE TITLE
MouseWheel not working on Walk navigation

### ISSUE THREAD

**Issue by janadamec1** [castle-engine/view3dscene#48]
MouseWheel works on Walk navigation only after you select Fly (where Wheel works) and then select Walk again.

Can be reproduced by opening demo-models/navigation/type_nav.wrl

Still I think walking using MouseWheel is very strange. I still feel it would be best to use it to Rotate Up/Down instead for all of us who navigate using mouse exclusively.

Regardless on resolving the MouseWheel for walking or tilting, **it is not possible to rotate the look even in view3dscene**. It is very frustrating. What about setting keyU / keyJ (or any standard key, PageUp perhaps?) as defaults for Input_UpRotate / Input_DownRotate in CastleCameras for all CGE apps?

**Comment by michaliskambi** [comment]
1. I fixed the issue of first mouse wheel not working for zoom, along with a bigger rework of walk/fly handling: https://github.com/castle-engine/view3dscene/commit/38380d6c25bef1aeb88c8383c02f2da36118353b

2. As for your own applications:

    Inputs are configurable in CGE, you can change them in your own applications, using e.g.:

    ```pascal
    MyWalkNavigation.ZoomEnabled := false; // this is already default in CGE
    MyWalkNavigation.Input_UpRotate.Assign(keyNone, keyNone, '', false, buttonLeft, mwUp);
    MyWalkNavigation.Input_DownRotate.Assign(keyNone, keyNone, '', false, buttonLeft, mwDown);
    ```

    or (simpler, if you don't care about initializing all input fields and want to just add mouse wheel):

    ```pascal
    MyWalkNavigation.ZoomEnabled := false; // this is already default in CGE
    MyWalkNavigation.Input_UpRotate.MouseWheel := mwUp;
    MyWalkNavigation.Input_DownRotate.MouseWheel := mwDown;
    ```

    I tested above, and we had a bug (assigning mouse wheel to Input_UpRotate/Input_DownRotate didn't work), it is now fixed in https://github.com/castle-engine/castle-engine/commit/6ff413b20cc28e9f74a236bcac60424ee6b040d1 . So above examples really work :)

3. As for what is best for view3dscene, CGE editor, and engine defaults:

    I did give it quite some thought, and I don't consider mouse wheel as a good choice (by default) to look up / down.

    Mouse wheel should 1. do zoom (yes -- this is practically the same as walking forward / backward in fly mode), 2. or change move speed, when in MouseLook mode.

    This applies to both CGE editor and in view3dscene, as I want them to be consistent for users. And my recent changes make them more consistent, e.g. mouse look is now easily available in view3dscene if you hold Right mouse button, just like in CGE editor, and mouse wheel then changes speed.

    This treatment of mouse wheel is:

    1. Intuitive to users. I did test CGE editor on other people, including professional 3D people :) Conclusions: Mouse wheel should really do a zoom, regardless of mode (examine or walk), this is intuitively expected by people.

    2. Consistent with other software. Blender, Unity, Gestaltor are examples of software I look upon closely. It's not a perfect correspondence of course (e.g. Blender has a special "fly mode" activated by Shift+~ instead of right click), but I believe people can see it is "analogous when it makes sense". They all use mouse wheel as described above (zoom, or change speed in mouse look mode e.g. when you hold right mouse button).

    3. Personally, I also think it's not comfortable to look up / down with mouse wheel (or some keys) anymore. I had a different point of view long time ago, when mouse was not always guaranteed, and you needed to provide some keys to look up / down. Nowadays, when everyone has mouse, mouse look is really a superior way to look around in 3D.

    For games, we provide by default a rather "conservative" input shortcuts, to not be surprising (so e.g. AWSD work by default, but not much more, with TCastleWalkNavigation) and encourage developers to activate mouse look to navigation on desktop (examples/fps_game, examples/physics/physics_explosion, examples/physics/physics_3d_shooter, ...).
    
These are the current shortcuts in view3dscene:

![Zrzut ekranu z 2023-02-27 03-20-58](https://user-images.githubusercontent.com/1076978/221463236-6730b5ec-f3a1-4549-994c-9efbd6d737ac.png)
