### ISSUE TITLE
HAnimDisplacer posted to wrong repo:

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#50]
https://github.com/castle-engine/castle-engine/issues/446

**Comment by coderextreme** [comment]
Actually, it might be in right place, I’ll have to check out to desktop at this point.

**Comment by michaliskambi** [comment]
Let's just have one issue, to centralize discussion. I'm closing this one, let's move to https://github.com/castle-engine/castle-engine/issues/446 . Whenever/however this is implemented, of course all X3D support done in CGE will also be available in view3dscene.
