### ISSUE TITLE
view3dscene should support HAnimMotion.name

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#58]
https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-IS.proof/Part01/components/hanim.html#HAnimMotion

See standard for HAnimMotion.name

**Comment by michaliskambi** [comment]
Thanks, fixed! 

As usual, give Jenkins a few hours and the "snapshot" version of view3dscene on https://castle-engine.io/view3dscene.php will contain the fix.

**Comment by coderextreme** [comment]
yep!
