### ISSUE TITLE
Screenshot to image

### ISSUE THREAD

**Issue by wwwjava** [castle-engine/view3dscene#61]
Hi, I get an error when trying "Screenshot to image(Transparent background)
![SharedScreenshot](https://github.com/castle-engine/view3dscene/assets/45557870/e390ac6e-eb57-42a9-b24a-3d3bc9e59449)

**Comment by michaliskambi** [comment]
Thank you, confirmed and fixed!

Background: The spaces in the filename (which get converted to `%20` along the way for URL) were confusing for the `Format` routine that scans the string for `%` placeholders like `%d`. Fixed to not apply formatting on the initial part. 

Tested, and now a 3D model with filename like `animate_camera something blah.x3dv` (2 spaces inside) has a (proposed) screenshot name like `animate_camera something blah_0.png` (or `animate_camera something blah_1.png` etc., the algorithm chooses first available number).

Please give Jenkins an ~hour from now, and the "snapshot" view3dscene version on https://castle-engine.io/view3dscene.php will contain the fix.
