### ISSUE TITLE
Lily 73 .x3dv model does not view well in view3dscene

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#63]
https://www.web3d.org/x3d-resources/content/examples/HumanoidAnimation/WinterAndSpring/Lily73Final0823Test2Index.html

.x3dv fails in view3dscene
.x3d succeeds in view3dscene
Is there an issue with conversion?

I am unsure what conversion is being used.

Thanks!

John

**Comment by michaliskambi** [comment]
The "Classic VRML" version on https://www.web3d.org/x3d-resources/content/examples/HumanoidAnimation/WinterAndSpring/Lily73Final0823Test2Index.html is indeed incorrect, view3dscene message 

```
...
VRML/X3D: Error when reading, will skip the rest of X3D file: Error at line 71 column 37: Incorrect USE clause: node name "Lily_humanoid_root" undefined
```

is IMHO clear. Opening it in text editor confirms it, the file contains

```
...
skeleton [
              USE Lily_humanoid_root
]
joints [
              DEF Lily_humanoid_root HAnimJoint {
                name "humanoid_root"
...
```

You cannot USE a name before you DEFined a name.

The X3D XML encoding version is correct, you can see it contains

```
<HAnimJoint DEF='Lily_humanoid_root'
``

**before** the name is used lower by 

```
<HAnimJoint USE='Lily_humanoid_root' containerField='skeleton'/>
```

The conversion has to try to preserve the order. Or to invert the place where DEF and USE happens. The first occurrence should always by DEF, the latter occurrence should be USE (that's how tovrmlx3d conversion works).

Please report is as an issue to https://www.web3d.org/x3d-resources/content/examples/HumanoidAnimation/WinterAndSpring/Lily73Final0823Test2Index.html authors.
