### ISSUE TITLE
Normals not converted to VRML with tovrmlx3d.exe when they are in a Blender X3D export.

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#64]
Apparently, tovrmlx3d.exe does not convert the Normal node, and normalpervertex field in an IndexedFaceSet as exported by Blender in X3D.  We are converting to classic with:

"${TOVRMLX3D}" --encoding classic "${PREFIX}".x3d > "${PREFIX}".x3dsource.x3dv

Please address this, otherwise I will have to suppress my normal animations.

(note: check the Normals checkbox in Blender before exporting, and don't triangulate)

I will try x3d-tidy and X3dToX3dvClassicVrmlEncoding.xslt but I'm hoping to match what's in a glTF converted with tovrmlx3d.exe.

Thanks!

**Comment by coderextreme** [comment]
This is more important than my HAnimHumanoid issue.  I have a workaround for that.  You may suggest to triangulate.  I don't know if that will mess up our skin coord info because there will be more indexes, so we'd like to keep what we have.

Thanks!

John

**Comment by michaliskambi** [comment]
CGE and view3dscene do preserve the `Normal` node in `normalPerVertex`. 

Please provide testcase if it doesn't work for you.

I tested now on 

```
#X3D V3.2 utf8
PROFILE Interchange

Shape {
    geometry IndexedFaceSet {
        normal Normal {
            vector [
                0 0 1,
                0 0 1,
                0 0 1,

            ]
        }
        normalPerVertex FALSE
    }
}
```

Converting (classic->xml) by 

```
tovrmlx3d aaa.x3dv --encoding=xml > aaa1.x3d
```

preserves `Normal` and `normalPerVertex`.

Converting (xml->classic) by 

```
tovrmlx3d aaa1.x3d --encoding=classic > aaa2.x3dv
```

again preserves `Normal` and `normalPerVertex`. This is the resulting file:


```
#X3D V3.2 utf8

PROFILE Interchange

META "source-previous" "aaa.x3dv"
META "generator" "tovrmlx3d, https://castle-engine.io/view3dscene.php#section_converting"
META "source" "aaa1.x3d"

Shape {
	geometry IndexedFaceSet {
		normalPerVertex FALSE
		normal Normal {
			vector [
				0 0 1,
				0 0 1,
				0 0 1,
			]
		}
	}
}
```

**Comment by coderextreme** [comment]
I'll have to get permission, but I have  a workaround working with x3d-tidy
now.
