### ISSUE TITLE
Error while closing

### ISSUE THREAD

**Issue by EmEiBee** [castle-engine/view3dscene#65]
When I have viewed a file (mostly STL) and close the viewer, I always get an error message:
(transcribed):
```
Exception "Exception":
Cannot use TCastleViewport. PositionToXxx when viewport has
effectively empty size. The typical solution is to add
TCastleViewport to some UI hierarchy, like
"Windows.Container.InsertFront(MyViewport)", although you
could also set TCastleViewport.Width/Height explicitly.
```
I have no idea about it...

System is a WIN10x64 22H2-19045.3324, AMD Ryzen 7 1700, 32GB RAM, NVIDIA GeForce GTX 1050 Ti, running UHD via DP

**Comment by michaliskambi** [comment]
Can you check does the issue still occur for you with the latest view3dscene "snapshot" from https://castle-engine.io/view3dscene.php ?

Background: We know about this issue, it was introduced (my mistake) on August 25th, and fixed ~1 week later on September the 1st. So if you downloaded view3dscene / CGE during that week, you'd indeed experience this error. But it should be fixed now.

**Comment by EmEiBee** [comment]
Japp! Now the error is gone!
Thank you very much for the fast response and assistance!
