### ISSUE TITLE
Truncation in HAnim animation section of classic VRML converted from glTF Blender export

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#66]
This likely isn't an issue, but I noticed some truncate "Shape" word segments replaced with "Sha" in some of the animation code.  AFAIK, the animations work great.  Just a bit of weirdness I noticed.

Here's the DEF:

                                        DEF node_t_Lily_RV7_Shape Transform {

And below are the Sha's
```
$ grep Lily lily_73/lily_73.gltfsource.x3dv |grep "Sha "
DEF CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha TimeSensor {
DEF CastleEncoded_SkinCoordInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha CoordinateInterpolator {
DEF CastleEncoded_SkinNormalInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha CoordinateInterpolator {
DEF CastleEncoded_ValueTrigger_setBBox_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha ValueTrigger {
```
```
$ grep Lily lily_73/lily_73.gltfsource.x3dv |grep "Sha\."
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.fraction_changed TO CastleEncoded_Animate_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha_node_t_Lily_RV7_Shape_translation.set_fraction
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.fraction_changed TO CastleEncoded_Animate_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha_node_t_Lily_RV7_Shape_rotation.set_fraction
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.fraction_changed TO CastleEncoded_Animate_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha_node_t_Lily_RV7_Shape_scale.set_fraction
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.fraction_changed TO CastleEncoded_SkinCoordInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.set_fraction
ROUTE CastleEncoded_SkinCoordInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.value_changed TO Coordinate.set_point
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.fraction_changed TO CastleEncoded_SkinNormalInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.set_fraction
ROUTE CastleEncoded_SkinNormalInterpolator_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.value_changed TO Normal.set_vector
ROUTE CastleEncoded_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.isActive TO CastleEncoded_ValueTrigger_setBBox_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.trigger
ROUTE CastleEncoded_ValueTrigger_setBBox_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.bboxCenter_changed TO Shape.set_bboxCenter
ROUTE CastleEncoded_ValueTrigger_setBBox_node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Shape$124$node_t_Lily_RV7_Sha.bboxSize_changed TO Shape.set_bboxSize
```

**Comment by michaliskambi** [comment]
Please attach a full testcase to reproduce, i.e. the input file (X3D or glTF) you use (the input you feed to tovrmlx3d or view3dscene).

We don't do any truncation of even long names in code, from what I can tell -- just looked at the source code. Also tested: the name with 720 characters was preserved by tovrmlx3d correctly.

**Comment by coderextreme** [comment]
This seems to be where it's coming from in the glTF:

                        "name":"node_t_Lily_RV7_Shape|node_t_Lily_RV7_Shape|node_t_Lily_RV7_Sha",
                        "samplers":[
                                {
                                        "input":7,
                                        "interpolation":"LINEAR",
                                        "output":8
                                },
                                {
                                        "input":9,
                                        "interpolation":"STEP",
                                        "output":10
                                },
                                {
                                        "input":9,
                                        "interpolation":"STEP",
                                        "output":11
                                }
                        ]

I'm unsure about the FBX/blend.  Ultimately, I would need to back to that.

Again, probably not an issue.

**Comment by coderextreme** [comment]
I was able to look directly at the FBX with strings:

$ strings /C/Users/john/Tufani/*fbx|grep Lily
node_t_Lily_RV7_Shape
mesh_t_Lily_RV7_Shape
mesh_t_Lily_RV7_Shape
node_t_Lily_RV7_Shape
mesh_t_Lily_RV7_Shape
humanoid_root|node_t_Lily_RV7_Shape|World0.usd|Base Layer
humanoid_root|node_t_Lily_RV7_Shape|World0.usd|Base Layer
node_t_Lily_RV7_Shape|node_t_Lily_RV7_Shape|World0.usd|Base Layer
node_t_Lily_RV7_Shape|node_t_Lily_RV7_Shape|World0.usd|Base Layer
humanoid_root|node_t_Lily_RV7_Shape|World0.usd|Base Layeru
humanoid_root|node_t_Lily_RV7_Shape|World0.usd|Base Layer.tak
node_t_Lily_RV7_Shape|node_t_Lily_RV7_Shape|World0.usd|Base Layer
node_t_Lily_RV7_Shape|node_t_Lily_RV7_Shape|World0.usd|Base Layer.tak

So perhaps it *is* an issue with glTF export!

John

**Comment by coderextreme** [comment]
Here is strings of .blend file:

$ strings /C/Users/john/Downloads/LILY_7_3_BLEND\ \(2\).blend |grep Lily
OBmesh_t_Lily_RV7_Shape
OBnode_t_Lily_RV7_Shape
MEmesh_t_Lily_RV7_Shape
ACnode_t_Lily_RV7_Shape|World0.usd|Base Layer
node_t_Lily_RV7_Shape
