### ISSUE TITLE
Any chance tovrmlx3d.exe can be made to use more CPU cores?  Thanks!

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#70]
![image](https://github.com/castle-engine/view3dscene/assets/705783/77e9c3ae-88eb-413f-9ff3-eecf73ab14f1)

I will look for option to increase number of CPUs and memory usage. I didn't see anything in the documentation I looked at. I will look for a FAQ. I'm using around 15% of the CPU and 2.6GB with tovrmlx3d (totaling 9GB on system, out of 32GB) of memory. It would be nice to use more memory and more cores.

x3d-tidy doesn't fare much better, it doesn't seem to be doing much of anything.

I know you want the data file.  See email with Katy.

Oh, good, tovrmlx3d finished!

Thanks!

**Comment by michaliskambi** [comment]
No, we don't plan at this point for conversion (reading or writing of X3D, in particular) to be done in threads and thus split in more cores. It would be a  very non-trivial task to parallelize parsing a single X3D file. I don't think any X3D browser is doing it either.

It should be possible in the future in CGE to make async reading of multiple models in parallel (see "30. Asynchronous loading of assets" https://castle-engine.io/roadmap#async ) but that will not help for reading just a single file.

We do plan to optimize memory usage (our X3D nodes eat way too much memory now).
