### ISSUE TITLE
consider more descriptive diagnostic when USE node is out of order

### ISSUE THREAD

**Issue by brutzman** [castle-engine/view3dscene#71]
If a USE node appears before the corresponding DEF, the following diagnostic appears:

- tovrmlx3d: Warning: VRML/X3D: Incorrect USE clause: node name "SKINCOORD" undefined

Suggest looking ahead to see if the DEF node occurs later in the scene, then noting that DEF node definition is out of order.  For example:

- tovrmlx3d: Warning: VRML/X3D: Incorrect USE clause: node name "SKINCOORD" is defined later in the scene, must occur before the corresponding USE

Sorry no example for this simple suggestion- uncovered it while debugging X3dToClassicVrml.xslt stylesheet with tovrmlx3d.exe and so the example will (hopefully) get fixed.

**Comment by michaliskambi** [comment]
Hm, while I can see it would be useful, it would be admittedly a significant effort to add this. 

"Looking ahead" is not doable (easily) -- we have really not yet parsed the rest of file (in either classic or XML encoding) at the moment when we resolve the USE="xxx" and report problems. 

Other solutions are also uneasy:

- We cannot move resolving USE="xxx" later, as in VRML you can have the same node name used multiple times (and USE="xxx" refers to last usage before this USE). So you need to know namespace at the exact place of USE="xxx" occurrence, if we want to support still older VRML.

- Leaving the warning reporting to later is most feasible. We could record "remember to make a warning about xxx" and after we finished parsing, "dump" all pending warnings. At this moment we can check if "xxx" was defined later.
 
     But this is also a code complication that I'm reluctant to do just for this simple case. And it will mean that warnings order gets mangled (currently warnings are in "natural" order, i.e. in the same sequence in which they occur).

Sorry, I'm going to have to close this one. I see the merit, but it is too much effort (additional code complexity) for too little gain (improving a warning message) IMHO. Of course if you still think it's critical to do, let's talk :)

**Comment by brutzman** [comment]
Makes sense.  Suggestion: soften the report so that the user understands a fixable problem might be present.  Could say

- tovrmlx3d: Warning: VRML/X3D: Incorrect USE clause: node name "SKINCOORD" undefined, or USE node appears before DEF node

Meanwhile a simple way to be sure would simply be to look for "DEF SKINCOORD" when flushing the rest of the file.

**Comment by michaliskambi** [comment]
For now I indeed just extended the warning message.
