### ISSUE TITLE
Metadata nodes are allowed as root nodes

### ISSUE THREAD

**Issue by brutzman** [castle-engine/view3dscene#72]
Specification sayeth:
- X3D 4.0 Architecture, ISO/IEC 19775-1:2023, 4 Concepts, 4.3.2 Root nodes
- https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-IS.proof/Part01/concepts.html#Rootnodes

Am testing X3dToClassicVrml stylesheet conversion by using tovrmlx3d.exe verification for following pair of test scenes:

- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter15Metadata/

- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter15Metadata/MetadataNodeExamplesX3D3.x3d
- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter15Metadata/MetadataNodeExamplesX3D3.x3dv

- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter15Metadata/MetadataNodeExamplesX3D4.x3d
- https://www.web3d.org/x3d/content/examples/X3dForWebAuthors/Chapter15Metadata/MetadataNodeExamplesX3D4.x3dv

Getting false-positive error:
```
ClassicVRML validation: tovrmlx3d.exe Chapter15Metadata//MetadataNodeExamplesX3D3.x3dv --validate --enable-downloads
tovrmlx3d: Warning: VRML/X3D: Node "MetadataString" is not allowed at the top level of the X3D file
tovrmlx3d: Warning: VRML/X3D: Error when reading, will skip the rest of X3D file: Error at line 55 column 33: Incorrect USE clause: node name "MyMetadataStringNode" undefined
```

Once this top-level root node problem is fixed, likely some other difficulties remain since these are tricky tests.  Will continue working on those.

Reminder: for XML encoding, X3D3 default containerField='metadata' and X3D4 default containerField='value'

**Comment by michaliskambi** [comment]
Thanks, fixed!

I somehow missed this X3D 4.0 change (our code was at X3D 3.3 level, https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/concepts.html#Rootnodes , and allowed only children nodes and LayerSet).

We allow now metadata nodes at root level, and `GeoOrigin` (also mentioned there) too.

I also made sure Pascal API to read metadata nodes at top-level is easy, developers can now use from Pascal `MyScene.RootNode.MetadataString['my_key']` , similar to our helper API on regular nodes ( https://castle-engine.io/blender#_custom_properties ).

**Comment by michaliskambi** [comment]
P.S. @brutzman I see that in your email 2023-07-18 in thread _"[x3d-public] "deep dive" on containerField and value fields for Metadata* node example"_ you mentioned

>     Hint: each of the Metadata nodes are allowed as top-level root nodes in a scene, if doing that be sure to explicitly define containerField='metadata'. 

Note that CGE/view3dscene don't care about `containerField` in this special case. I.e. it doesn't matter what is the `containerField` (and in which X3D version we are) for metadata nodes present at top-level.

**Comment by michaliskambi** [comment]
> Reminder: for XML encoding, X3D3 default containerField='metadata' and X3D4 default containerField='value'

I had this in private TODO for a long time now, following our talk on _" [x3d-public] "deep dive" on containerField and value fields for Metadata* node examples"_. Sorry, I didn't yet get to do this fix, but I added a separate GH issue to track it: 

https://github.com/castle-engine/view3dscene/issues/78 

You can subscribe to that issue to be notified when I'll get to it, should be later this month.
