### ISSUE TITLE
skinCoord precedes skin in HAnimHumanoid

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#83]
Per Don Brutzman.  What this means to me is that skinCoord and skinNormal should precede skin in HAnimHumanoid, and if misordered, a warning should be issued by view3dscene/tovrmlx3d.  You are welcome to disagree.  Please join the discussion on x3d-public.

“Further please note that the functional descriptions are provided in the HAnim 2.0 standard:

 

HAnim 2.0 Part 1:  Humanoid animation (HAnim) architecture, 6 Object interfaces, 6.2 Humanoid
https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid
 

“The skin field contains one or more indexed mesh definitions. Those indexed mesh definitions utilize the point and normal data that is defined within the skinCoord and skinNormal fields, respectively, of the Humanoid object. This field is defined as an generic type for which the specific representation is defined by each binding to a presentation system. [Annex C VRML binding](https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/VRMLInterface.html) contains a binding for VRML. [Annex D X3D binding](https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/X3DInterface.html) describes the Humanoid animation component of X3D specified in [ISO/IEC 19775-1](https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/bibliography.html#I19775_1).”

**Comment by michaliskambi** [comment]
The fields in X3D nodes can be specified in any order. That is, in the specification https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid they are alphabetical, but actual X3D file can specify then in any order. We have thousands of X3D models showing this, and all X3D browsers allow any order :)

And I haven't seen Don saying anything that contradicts this in x3d-public.

The thread on x3d-public is long and I don't have capacity to join it I'm afraid. If you think that view3dscene is doing anything that is invalid (with respect to X3D spec, or just common sense) please attach a testcase.

**Comment by michaliskambi** [comment]
I did post in _"Re: [x3d-public] What are valid children of HAnimHumanoid.skin?"_ thread in the end, to clarify what and why we do.

**Comment by coderextreme** [comment]
You will get another issue if someone is using x3d.py output with
Humanoids.   There’s no issue with view3dscene as it stands, I am trying to
stop future users of x3d.py AND view3dscene from having similar issues than
I did.  I’d rather have one pain, than multiple pains.  Wouldn’t you
agree?  Treatment is one thing, but cure is better.

As for order of skin/skinCoord/skinNormal, please read the text of the
specification that I quoted Don quoting the standard, don’t just look at
“alphabetical” order.

https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/ObjectInterfaces.html#Humanoid

It’s a ways down from the node interface.  I’ll requote it below.  I’m not
an expert standards reader.  AFAICT, all the skin/skinCoord/skinNormal
examples are broken according to my reading of the standard.  I think
that’s what Don was alluding to when he quoted the standard.  I can forward
you the message where he quoted the standards.

The *skin* field contains one or more indexed mesh definitions. Those
indexed mesh definitions utilize the point and normal data that is defined
within the *skinCoord* and *skinNormal* fields, respectively, of the
Humanoid object. This field is defined as an generic type for which the
specific representation is defined by each binding to a presentation system.
 Annex C VRML binding
<https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/VRMLInterface.html>
 contains a binding for VRML. Annex D X3D binding
<https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/X3DInterface.html>
 describes the Humanoid animation component of X3D specified in ISO/IEC
19775-1
<https://www.web3d.org/documents/specifications/19774/V2.0/Architecture/bibliography.html#I19775_1>
.


John
