### ISSUE TITLE
Direct use of /tmp

### ISSUE THREAD

**Issue by PeterBBBBB** [castle-engine/view3dscene#84]
Please consider avoiding direct use of the /tmp directory as this can easily be accessed by other users. Could use a tmp directory in the build tree, or use mktemp.

See; 
https://salsa.debian.org/pascal-team/view3dscene/-/blob/master/debian/patches/fix__run_test_once.sh__to_not_depend_on_tool_in_cge.patch

**Comment by michaliskambi** [comment]
In case of `jenkins_scripts/run_test_on_model.sh`, we don't need to use a temporary file at all. We can hold the necessary value in bash environment variable. I changed the script to do it.
