### ISSUE TITLE
tovrmlx3d - Support for file content in stdin

### ISSUE THREAD

**Issue by dimitribalasoiu** [castle-engine/view3dscene#86]
In tovrmlx3d, it would be nice to add the possibility of reading files from the standard input, i.e. :
`tovrmlx3d >> out.xml < cat in.x3d`

**Comment by michaliskambi** [comment]
This was available in the past, but then removed. But it makes sense to bring it back :), with new additional option described below:

The way it works now:

- You still have to pass a filename/URL on the command-line, but it can be dash (`-`) to indicate "this file comes from stdin".

    ( Reason behind doing it this way, not just accepting "no arguments" as "read from stdin": This makes it a bit less confusing for users who may not be familiar with the concept of "reading from stdin", and would be surprised that `tovrmlx3d` run from console without any arguments just "hangs" (while it is actually waiting for input on stdin). )

- Moreover, I added command-line option `--stdin-url` to indicate input file type (X3D classic by default) and indicate the URL from which we resolve relative URLs (e.g. binary blobs in glTF, which we need to read to convert glTF to X3D).

    By default it is `stdin.x3dv` in current dir. Pass e.g. `--stdin-url=/home/michalis/models/my-model.gltf` to treat input as glTF, and look for glTF binary blobs in `/home/michalis/models/` dir.

**Comment by michaliskambi** [comment]
I added dedicated section about tovrmlx3d to document its features on https://castle-engine.io/view3dscene.php#section_tovrmlx3d , mentioning also this stdin support.

As usual, the "snapshot" version of view3dscene should be available on https://castle-engine.io/view3dscene.php shortly. It will contain also this `tovrmlx3d` improvement. I see it is already in-progress, waits now only for Raspberry Pi 32-bit build. It should be done in "5 minutes optimistically", let's make it "1 hour pessimistically".

**Comment by coderextreme** [comment]
Thanks, Michalis, I will download a new version.  I'm eager to try new stdin option with view3dscene.
