### ISSUE TITLE
EAccessViolation

### ISSUE THREAD

**Issue by coderextreme** [castle-engine/view3dscene#89]
On this file:  [BuggyForMichalis.x3dv](https://github.com/coderextreme/WinterAndSpring/blob/main/BuggyForMichalis.x3dv)

Let me know if you need the original.

I'm going to download latest view3dscene to check again.

John

**Comment by coderextreme** [comment]
![image](https://github.com/castle-engine/view3dscene/assets/705783/edfb158c-451a-4fc7-8bc9-9f1696b7eb81)

**Comment by michaliskambi** [comment]
Confirmed, I can reproduce the EAccessViolation on the file. With latest view3dscene, on Linux/x86_64.

No need to provide anything more, I have all I need to debug it.

Thanks, will let you know when this is fixed!

**Comment by michaliskambi** [comment]
Thank you, EAccessViolation on https://github.com/coderextreme/WinterAndSpring/blob/main/BuggyForMichalis.x3dv fixed.

As usual, the fix will be available in view3dscene "snapshot" version on https://castle-engine.io/view3dscene.php shortly, once the new version passes some automatic tests. You can observe the page https://github.com/castle-engine/castle-engine/compare/snapshot...master , when it will no longer contain the commit _"Secure generating log message when event ROUTE used multiple times in..."_ then this commit is part of the released binaries.

Note: the model reports other warnings, which I didn't investigate now but assume are valid (report a separate issue if the warning is invalid). About missing node names or duplicate node names.

![obraz](https://github.com/castle-engine/view3dscene/assets/1076978/b91c7b76-e0bf-4fee-b2fb-5d828188ced9)

**Comment by coderextreme** [comment]
Our latest files VRML are here, there may be some outstanding problems that may need to be fixed.  I will try to get to downloading the new version of view3dscene.

View3dScene has worked very well for the WinterAndSpring project, thanks for all your assistance.

[WinterAndSpring output folder](https://github.com/coderextreme/WinterAndSpring/tree/main/OutputDir8)

If you want to have some fun, convert JavaScript Perl and shell source code to Pascal!  This is mostly prototype code for translating templates text files to Humanoids!
