### ISSUE TITLE
LoadSensor child nodes have containerField=children in X3D 4.0

### ISSUE THREAD

**Issue by brutzman** [castle-engine/view3dscene#90]
LoadSensor child nodes have containerField=children in X3D 4.0 as part of a regularization of several field names.  They are described here:

- X3D Scene Authoring Hints, Field name changes for improved consistency in X3D4
- https://www.web3d.org/x3d/content/examples/X3dSceneAuthoringHints.html#fieldNameChanges

Test scene available online:
- https://www.web3d.org/x3d/content/examples/HumanoidAnimation/WinterAndSpring/MainStageIndex.html
- https://www.web3d.org/x3d/content/examples/HumanoidAnimation/WinterAndSpring/MainStage.x3d

**Comment by michaliskambi** [comment]
Fixed, tested on the linked testcase, thank you for reporting!

Note: The wording of the statements on https://www.web3d.org/x3d/content/examples/X3dSceneAuthoringHints.html#fieldNameChanges was a bit confusing for me at first:

> LoadSensor: change unnecessarily different field name containerField='watchList' and rename as containerField='children' instead. Child node restrictions can achieve a functionally equivalent effect and improve the object-oriented design.

It would be more obvious to call it _"Change the LoadSensor field name `watchList` to `children`. In effect, typical child nodes, that have `containerField='children'`, will automatically match it, and there will be no need to provide explicit `containerField` in the X3D XML files"_.

Anyhow, looking at difference between `LoadSensor` in X3D 3.3 and 4 it is clear to me (and it's a good change, thanks for taking care of it).

https://www.web3d.org/documents/specifications/19775-1/V4.0/Part01/components/networking.html#LoadSensor
https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/networking.html#LoadSensor

**Comment by michaliskambi** [comment]
As usual, the fix will be reflected in view3dscene from snapshots on https://castle-engine.io/view3dscene.php . It will be available there in a few hours, after the new code passes some automatic checks. 

You can observe this page: https://github.com/castle-engine/castle-engine/compare/snapshot...master , when it will *no longer* contain the commit called "_Account for some field renames in X3D 4.0 (LoadSensor.children..._" it means that the commit is part of the release.
