### ISSUE TITLE
VRML/X3D: Plug name "main_texture_apply " not declared (in shader type "Fragment")

### ISSUE THREAD

**Issue by elmkni** [castle-engine/view3dscene#91]
Hi Michalis,

it's me, Elmar, again...

I've just tested the newest snapshot of [View3DScene](https://jenkins.castle-engine.io/public/builds/view3dscene/view3dscene-4.3.0-win64-x86_64.zip) (01-Apr-2024 21:40) and got following error message with a scene that worked yesterday!

```
1 warnings:

VRML/X3D: Plug name "main_texture_apply " not declared (in shader type "Fragment")

Scene URL: "file:///D:/Installer/Programming/R/test/create_icosidodecahedron_files.x3dv".
Use "File->View Warnings" menu to view these warnings again.
```
What's going on?  -- The problem comes with all files of mine that make use of an effect shader! -- Is this a bad 1st April joke?

Please help!

With best regards,

Elmar

P.S. here is my test file: [create_icosidodecahedron_files.x3dv.zip](https://github.com/castle-engine/view3dscene/files/14835755/create_icosidodecahedron_files.x3dv.zip)

**Comment by michaliskambi** [comment]
Thanks for reporting. I saw I indeed broke it in https://github.com/castle-engine/castle-engine/commit/a4f36766f06dc7109b66ac8d46142831c74e81f2 (27th March, last week).

I just fixed it.

I also added automatic test so the problem will not return in the future.

As usual, the snapshots on https://castle-engine.io/view3dscene.php will contain the fix automatically in a few hours. You can observe the page https://github.com/castle-engine/castle-engine/compare/snapshot...master -- when this page will *no longer show the commit* "Fix FindPlugName in case plug name is followed by space" -> this means this fix is now part of the snapshots downloadable from https://castle-engine.io/view3dscene.php .

> What's going on? -- The problem comes with all files of mine that make use of an effect shader! -- Is this a bad 1st April joke?

Please, there's no need for such statements. Of course it's not a joke.

It is just a bug, which happens in all software. We've done tests, we have automatic tests too, but sometimes bugs can still slip through (in this case an extra space between `PLUG_main_texture_apply` and `(` actually made a difference, even though it should not).

I'm fixing regressions and serious bugs as soon as possible. It took me 62 minutes to fix this one. Please show a bit of patience :)

**Comment by elmkni** [comment]
Hi, Michalis!

### Thank You very much for the quick fix !

**I did not mean to insult You in any way** -- I was mereley trying to be funny ... and failed -- sorry!

With best regards,

Elmar
